//! Regenerate the TSS vectors recorded in `PROTOCOL.md` and
//! `core/tests/vectors/tss-v1.json`.
//!
//! ```sh
//! cargo run -p pocketskynet-tss --example vector --release
//! ```
//!
//! Threshold signing is nondeterministic (the nonce is jointly random), so
//! these vectors cannot be regenerated byte-for-byte — a fresh run records a
//! fresh, equally valid ceremony. What the recorded vector pins is the
//! *verification* side: recovery, low-s, and transaction assembly, through
//! code that knows nothing about MPC.

use pocketskynet_core::{eip191, LegacyTransaction, WalletAddress};
use pocketskynet_tss::{dkg, eth, sign};

#[tokio::main]
async fn main() {
    let (t, n) = (2u16, 3u16);
    let eid = pocketskynet_tss::fresh_eid().unwrap();
    let shares = dkg::run_dkg(t, n, eid, |p| eprintln!("dkg: {p:?}"))
        .await
        .unwrap();
    let address = eth::eth_address(&shares[0]).unwrap();

    // 1. EIP-191 message vector, signed by parties {0, 2}.
    let message = "PocketSkynet TSS vector v1";
    let prehash = eip191::eip191_digest(message);
    let signers: Vec<(u16, pocketskynet_tss::Share)> = [0usize, 2]
        .iter()
        .map(|&i| (i as u16, shares[i].clone()))
        .collect();
    let sig = sign::sign_prehash(&signers, prehash, pocketskynet_tss::fresh_eid().unwrap())
        .await
        .unwrap();
    assert_eq!(
        eip191::recover_address(message, &sig.to_hex()).unwrap(),
        address
    );

    // 2. Transaction vector: same wallet signs a fixed EIP-155 sighash.
    let tx = LegacyTransaction {
        nonce: 9,
        gas_price: 5_000_000_000_000,
        gas_limit: 21_000,
        to: Some(WalletAddress::new("0x3535353535353535353535353535353535353535").unwrap()),
        value: 1_000_000_000_000_000_000,
        data: vec![],
        chain_id: 338,
    };
    let sighash = tx.sighash();
    let tx_sig = sign::sign_prehash(&signers, sighash, pocketskynet_tss::fresh_eid().unwrap())
        .await
        .unwrap();
    let signed = tx.sign_with_signature(&tx_sig.rs_bytes(), tx_sig.v);

    println!(
        "{}",
        serde_json::json!({
            "address": address.as_str(),
            "threshold": t,
            "parties": n,
            "signerSet": [0, 2],
            "message": message,
            "messageSignature": sig.to_hex(),
            "tx": {
                "nonce": 9,
                "gasPrice": "5000000000000",
                "gasLimit": 21000,
                "to": "0x3535353535353535353535353535353535353535",
                "value": "1000000000000000000",
                "data": "0x",
                "chainId": 338,
                "sighash": format!("0x{}", hex::encode(sighash)),
                "r": format!("0x{}", hex::encode(tx_sig.r)),
                "s": format!("0x{}", hex::encode(tx_sig.s)),
                "recoveryId": tx_sig.v,
                "raw": signed.raw_hex(),
                "hash": signed.hash_hex(),
            },
        })
    );
}
