//! Unit tests against the canonical protocol vectors
//! (`app/core/tests/vectors/protocol-v1.json`, generated by the Rust suite).
//!
//! Covered here: every `eip191[]` vector (digest, signature, address),
//! `wallet.privateKeyImports` and `wallet.eip55`, the `msgHash` plaintext
//! vectors, the `ecdh` checkpoint, and Keccak-256 edge cases.
//!
//! `wallet.accounts` derive from a BIP-39 mnemonic via BIP-32; mnemonic
//! import is out of scope for this client (it authenticates with a raw
//! private key), so those vectors are not exercised — see README.md.

const std = @import("std");
const ps = @import("pocketskynet");

const Keccak256 = std.crypto.hash.sha3.Keccak256;

// -- vector loading ---------------------------------------------------------

const vectors_rel_path = "app/core/tests/vectors/protocol-v1.json";

fn loadVectorsText(gpa: std.mem.Allocator, io: std.Io) ![]u8 {
    if (ps.transport.getEnv("POCKETSKYNET_REPO")) |root| {
        const path = try std.fs.path.join(gpa, &.{ root, vectors_rel_path });
        defer gpa.free(path);
        return std.Io.Dir.cwd().readFileAlloc(io, path, gpa, .limited(16 << 20));
    }
    // Walk up from cwd until the repo root (the directory holding `app/`).
    var prefix: std.ArrayList(u8) = .empty;
    defer prefix.deinit(gpa);
    var depth: usize = 0;
    while (depth < 12) : (depth += 1) {
        const path = try std.fmt.allocPrint(gpa, "{s}{s}", .{ prefix.items, vectors_rel_path });
        defer gpa.free(path);
        if (std.Io.Dir.cwd().readFileAlloc(io, path, gpa, .limited(16 << 20))) |text| {
            return text;
        } else |_| {}
        try prefix.appendSlice(gpa, "../");
    }
    std.debug.print(
        "could not find {s} above the current directory; set POCKETSKYNET_REPO\n",
        .{vectors_rel_path},
    );
    return error.VectorsNotFound;
}

var cached_vectors: ?std.json.Parsed(std.json.Value) = null;

fn vectors() !std.json.Value {
    if (cached_vectors == null) {
        // The cache deliberately lives for the whole test binary; parsed
        // vector strings are borrowed by every test below.
        const gpa = std.heap.page_allocator;
        const text = try loadVectorsText(gpa, std.testing.io);
        defer gpa.free(text);
        cached_vectors = try std.json.parseFromSlice(std.json.Value, gpa, text, .{});
    }
    return cached_vectors.?.value;
}

fn field(v: std.json.Value, key: []const u8) std.json.Value {
    return v.object.get(key) orelse std.debug.panic("missing vector field '{s}'", .{key});
}

fn str(v: std.json.Value, key: []const u8) []const u8 {
    return field(v, key).string;
}

// -- eip191[] ---------------------------------------------------------------

test "eip191: every vector reproduces digest, signature and address byte-exactly" {
    const root = try vectors();
    const list = field(root, "eip191").array;
    try std.testing.expect(list.items.len >= 7);

    for (list.items) |entry| {
        const message = str(entry, "message");
        const utf8_len: usize = @intCast(field(entry, "messageUtf8Len").integer);
        try std.testing.expectEqual(utf8_len, message.len);

        const key = try ps.secp.PrivateKey.fromHex(str(entry, "privateKeyHex"));

        // Signing key belongs to the stated address.
        const addr_hex = key.addressHex();
        try std.testing.expectEqualStrings(str(entry, "address"), &addr_hex);

        // Digest.
        const digest = ps.eip191.digest(message);
        const expected_digest = try ps.hex.decodeFixed(32, str(entry, "digestHex"));
        try std.testing.expectEqualSlices(u8, &expected_digest, &digest);

        // Signature, byte-exact including low-S and v.
        const sig_hex = ps.eip191.personalSignHex(message, key);
        try std.testing.expectEqualStrings(str(entry, "signatureHex"), &sig_hex);

        // And it recovers back to the signer.
        const sig = try ps.secp.Signature.fromWireHex(&sig_hex);
        const recovered = try ps.secp.recoverAddress(digest, sig);
        const recovered_hex = ps.secp.addressToHex(recovered);
        try std.testing.expectEqualStrings(str(entry, "address"), &recovered_hex);
    }
}

test "eip191: the unicode vector's length is bytes, not characters" {
    const root = try vectors();
    const list = field(root, "eip191").array;
    var found = false;
    for (list.items) |entry| {
        if (!std.mem.eql(u8, str(entry, "name"), "unicode-length-is-bytes")) continue;
        found = true;
        const message = str(entry, "message");
        const byte_len: usize = @intCast(field(entry, "messageUtf8Len").integer);
        const char_count = try std.unicode.utf8CountCodepoints(message);
        try std.testing.expectEqual(byte_len, message.len);
        try std.testing.expect(char_count < byte_len); // 12 chars, 15 bytes
    }
    try std.testing.expect(found);
}

// -- wallet ------------------------------------------------------------------

test "wallet.privateKeyImports: public key, address and EIP-55 form" {
    const root = try vectors();
    const list = field(field(root, "wallet"), "privateKeyImports").array;
    try std.testing.expect(list.items.len >= 3);

    for (list.items) |entry| {
        const key = try ps.secp.PrivateKey.fromHex(str(entry, "privateKeyHex"));

        const pub_key = key.publicKeyUncompressed();
        var pub_hex: [130]u8 = undefined;
        ps.hex.encode(&pub_hex, &pub_key);
        try std.testing.expectEqualStrings(str(entry, "publicKeyUncompressedHex"), &pub_hex);

        const addr_hex = key.addressHex();
        try std.testing.expectEqualStrings(str(entry, "address"), &addr_hex);

        const checksummed = ps.secp.eip55Checksum(key.address());
        try std.testing.expectEqualStrings(str(entry, "addressChecksummed"), &checksummed);
    }
}

test "wallet.eip55: checksum vectors" {
    const root = try vectors();
    const list = field(field(root, "wallet"), "eip55").array;
    try std.testing.expect(list.items.len >= 6);
    for (list.items) |entry| {
        const lower = str(entry, "lower");
        const addr = try ps.hex.decodeFixed(20, lower);
        const checksummed = ps.secp.eip55Checksum(addr);
        try std.testing.expectEqualStrings(str(entry, "checksummed"), &checksummed);
    }
}

// -- msgHash ----------------------------------------------------------------

test "msgHash.plaintext: SHA-256 of the trimmed content" {
    const root = try vectors();
    const list = field(field(root, "msgHash"), "plaintext").array;
    try std.testing.expect(list.items.len >= 3);
    for (list.items) |entry| {
        const content = str(entry, "content");
        const hash = ps.msghash.msgHashPlaintext(content);
        try std.testing.expectEqualStrings(str(entry, "msgHashHex"), &hash);
        if (entry.object.get("trimmedTo")) |trimmed| {
            try std.testing.expectEqualStrings(trimmed.string, ps.msghash.trim(content));
        }
    }
}

// -- ECDH checkpoint --------------------------------------------------------

test "ecdh: shared secret is the unhashed X coordinate" {
    const root = try vectors();
    const list = field(root, "ecdh").array;
    for (list.items) |entry| {
        const key = try ps.secp.PrivateKey.fromHex(str(entry, "privateKeyHex"));
        const peer = try ps.hex.decodeFixed(65, str(entry, "peerPublicKeyHex"));
        const shared = try ps.secp.ecdhSharedX(key, peer);
        var shared_hex: [64]u8 = undefined;
        ps.hex.encode(&shared_hex, &shared);
        try std.testing.expectEqualStrings(str(entry, "sharedXHex"), &shared_hex);
    }
}

// -- Keccak-256 edge cases --------------------------------------------------

fn keccakHex(data: []const u8) [64]u8 {
    var digest: [32]u8 = undefined;
    Keccak256.hash(data, &digest, .{});
    var out: [64]u8 = undefined;
    ps.hex.encode(&out, &digest);
    return out;
}

test "keccak256: empty input uses original 0x01 padding, not SHA-3's 0x06" {
    // The canonical Ethereum empty hash.
    try std.testing.expectEqualStrings(
        "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
        &keccakHex(""),
    );
    // NIST SHA3-256("") differs — the padding byte is the only difference.
    var sha3_digest: [32]u8 = undefined;
    std.crypto.hash.sha3.Sha3_256.hash("", &sha3_digest, .{});
    var sha3_hex: [64]u8 = undefined;
    ps.hex.encode(&sha3_hex, &sha3_digest);
    try std.testing.expectEqualStrings(
        "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a",
        &sha3_hex,
    );
    try std.testing.expect(!std.mem.eql(u8, &keccakHex(""), &sha3_hex));
}

test "keccak256: published reference values" {
    try std.testing.expectEqualStrings(
        "4e03657aea45a94fc7d47ba826c8d667c0d1e6e33a64a036ec44f58fa12d6c45",
        &keccakHex("abc"),
    );
    try std.testing.expectEqualStrings(
        "4d741b6f1eb29cb2a9b9911c82f56fa8d73b04959d3d9d222895df6c0b28aa15",
        &keccakHex("The quick brown fox jumps over the lazy dog"),
    );
    try std.testing.expectEqualStrings(
        "578951e24efd62a3d63a86f7cd19aaa53c898fe287d2552133220370240b572d",
        &keccakHex("The quick brown fox jumps over the lazy dog."),
    );
}

test "keccak256: multi-block input is pinned by an external vector" {
    // The login-challenge EIP-191 vector hashes prefix + 297-byte message =
    // 325 bytes — more than two 136-byte rate blocks — and its digest was
    // produced by ethers, not by this code.
    const root = try vectors();
    const list = field(root, "eip191").array;
    var checked = false;
    for (list.items) |entry| {
        if (!std.mem.eql(u8, str(entry, "name"), "login-challenge")) continue;
        const message = str(entry, "message");
        try std.testing.expect(ps.eip191.prefix.len + 3 + message.len > 2 * 136);
        const digest = ps.eip191.digest(message);
        const expected = try ps.hex.decodeFixed(32, str(entry, "digestHex"));
        try std.testing.expectEqualSlices(u8, &expected, &digest);
        checked = true;
    }
    try std.testing.expect(checked);
}

test "keccak256: streaming equals one-shot at and around the rate boundary" {
    // The sponge rate for Keccak-256 is 136 bytes. Bugs at the absorb
    // boundary show up as a divergence between chunked and one-shot hashing
    // at exactly these lengths.
    const lengths = [_]usize{ 0, 1, 135, 136, 137, 271, 272, 273, 500 };
    var data: [500]u8 = undefined;
    for (&data, 0..) |*b, i| b.* = @truncate(i *% 31 +% 7);

    for (lengths) |len| {
        var one_shot: [32]u8 = undefined;
        Keccak256.hash(data[0..len], &one_shot, .{});

        // Absorb in awkward chunk sizes.
        var st = Keccak256.init(.{});
        var offset: usize = 0;
        var chunk: usize = 1;
        while (offset < len) {
            const take = @min(chunk, len - offset);
            st.update(data[offset .. offset + take]);
            offset += take;
            chunk = (chunk * 3 + 1) % 40 + 1;
        }
        var streamed: [32]u8 = undefined;
        st.final(&streamed);

        try std.testing.expectEqualSlices(u8, &one_shot, &streamed);
    }

    // Distinct lengths of the same repeated byte must hash differently
    // (a missing-final-block bug would collide 135/136/137).
    const aa: [137]u8 = @splat('a');
    var h135: [32]u8 = undefined;
    var h136: [32]u8 = undefined;
    var h137: [32]u8 = undefined;
    Keccak256.hash(aa[0..135], &h135, .{});
    Keccak256.hash(aa[0..136], &h136, .{});
    Keccak256.hash(aa[0..137], &h137, .{});
    try std.testing.expect(!std.mem.eql(u8, &h135, &h136));
    try std.testing.expect(!std.mem.eql(u8, &h136, &h137));
    try std.testing.expect(!std.mem.eql(u8, &h135, &h137));
}
