//! Deterministic identity tiles.
//!
//! Why this lives in the client and not on the server: an avatar that is a pure
//! function of an identifier needs no storage, no upload, no moderation, and no
//! extra request — and it is *stable*, so a wallet you have seen before is
//! recognisable before you have read a single character of its address.
//!
//! Two outputs, both from one djb2 hash of the normalised seed:
//!
//! * [`monogram_for`] — the two characters drawn on the tile. For a wallet
//!   address they are the *leading two hex digits of the address itself*, so
//!   the tile can be checked against the `0x9f2a…` beside it rather than being
//!   an unrelated decoration. For anything else (room ids, which all begin
//!   `room_` and would otherwise every one of them read `RO`) they are two
//!   base-36 characters taken from the hash.
//! * [`hue_for`] — the tile colour, read from the *high* bits so it is
//!   decorrelated from the monogram: two accounts that collide on the letters
//!   almost never collide on the colour.
//!
//! Lightness and chroma are fixed in `app.css` (in OKLCH, so every hue lands on
//! the same perceptual lightness and the white monogram clears AA on all 360 of
//! them). The hue varies colour only, never legibility.

/// djb2 over UTF-16 code units, wrapping at 32 bits.
///
/// Bit-identical to the JavaScript original `((hash << 5) + hash + c) >>> 0`.
/// The `>>> 0` coerces to 32 bits every iteration, which is exactly what
/// `wrapping_mul`/`wrapping_add` on `u32` do; and `encode_utf16` reproduces the
/// JS iteration unit (a `String` in JS is a sequence of UTF-16 code units, not
/// scalar values). For hex addresses every unit is ASCII so the distinction is
/// moot — it matters only if this is ever fed a non-ASCII seed.
pub fn djb2(s: &str) -> u32 {
    s.encode_utf16()
        .fold(5381u32, |h, u| h.wrapping_mul(33).wrapping_add(u as u32))
}

/// Lowercase first, *then* strip `0x`, so an uppercase `0X…` prefix is also
/// removed and `0XAB…` and `0xab…` are one identity rather than two.
fn normalise(seed: &str) -> String {
    let lower = seed.to_ascii_lowercase();
    lower.strip_prefix("0x").unwrap_or(&lower).to_owned()
}

const BASE36: [u8; 36] = *b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

/// The two characters drawn on an identity tile, uppercased.
///
/// Never panics and never returns an empty string: this is display code, and a
/// tile with nothing on it is indistinguishable from a rendering failure.
pub fn monogram_for(seed: &str) -> String {
    let s = normalise(seed);
    let head: Vec<char> = s.chars().take(2).collect();

    // A wallet address: show its own leading hex, so the tile and the address
    // beside it can be read as the same thing.
    if head.len() == 2 && s.len() >= 8 && s.chars().all(|c| c.is_ascii_hexdigit()) {
        return head.into_iter().flat_map(char::to_uppercase).collect();
    }

    // Everything else: two base-36 characters of the hash. 1 296 combinations,
    // taken from the low bits so they stay decorrelated from the hue.
    let h = djb2(&s);
    let a = BASE36[(h % 36) as usize] as char;
    let b = BASE36[((h / 36) % 36) as usize] as char;
    [a, b].into_iter().collect()
}

/// Tile hue (0..359).
///
/// Uses `>> 8` so the hue reads bits the monogram never touches.
pub fn hue_for(seed: &str) -> u16 {
    if seed.is_empty() {
        return 0;
    }
    ((djb2(&normalise(seed)) >> 8) % 360) as u16
}

/// The operator faces — half human, half endoskeleton. Generated by
/// `tools/genart.py`; the names here are the file stems under `static/img/`,
/// so the two lists are one contract and must not drift.
pub const OPERATOR_ART: [&str; 10] = [
    "op-amber",
    "op-cyan",
    "op-crimson",
    "op-emerald",
    "op-violet",
    "op-gold",
    "op-steel",
    "op-rose",
    "op-teal",
    "op-bronze",
];

/// The room sigils — pure machine, never a face. Counts are coprime with
/// [`OPERATOR_ART`] so a person and a room do not travel as a fixed pair.
pub const ROOM_ART: [&str; 8] = [
    "room-skull",
    "room-visor",
    "room-core",
    "room-sentinel",
    "room-hunter",
    "room-relay",
    "room-warden",
    "room-cipher",
];

/// The chooseable profile gallery — half human, half terminator, where the
/// human half carries a characteristic (a coder's glasses, a chef's toque…)
/// and each characteristic exists as a man and as a woman. Generated by
/// `tools/genart.py::PROFILE_CHARACTERS`; the slugs here are what
/// `profileImage` stores on the wire as `preset:<slug>`, so this list is a
/// contract with both the asset manifest and the server's stored values.
pub const PROFILE_ART: [&str; 20] = [
    "tp-coder-m",
    "tp-coder-f",
    "tp-soldier-m",
    "tp-soldier-f",
    "tp-medic-m",
    "tp-medic-f",
    "tp-pilot-m",
    "tp-pilot-f",
    "tp-artist-m",
    "tp-artist-f",
    "tp-scientist-m",
    "tp-scientist-f",
    "tp-chef-m",
    "tp-chef-f",
    "tp-athlete-m",
    "tp-athlete-f",
    "tp-musician-m",
    "tp-musician-f",
    "tp-detective-m",
    "tp-detective-f",
];

/// A human-readable name for a gallery slug: `tp-coder-f` → "Coder — woman".
/// Used for `aria-label`/`title` in the picker; the images themselves are the
/// interface, so this stays a mechanical derivation rather than i18n surface.
pub fn profile_art_label(slug: &str) -> String {
    let bare = slug.strip_prefix("tp-").unwrap_or(slug);
    let (character, sex) = match bare.rsplit_once('-') {
        Some((c, "m")) => (c, "man"),
        Some((c, "f")) => (c, "woman"),
        _ => (bare, ""),
    };
    let mut label: String = character
        .chars()
        .enumerate()
        .map(|(i, c)| if i == 0 { c.to_ascii_uppercase() } else { c })
        .collect();
    if !sex.is_empty() {
        label.push_str(" — ");
        label.push_str(sex);
    }
    label
}

/// Resolve a stored `profileImage` value to an image `src`, or `None` when
/// the value is absent/unrecognised and the hash-derived tile should show.
///
/// Only two shapes resolve — a known gallery slug behind `preset:`, or a
/// same-origin `/api/images/…` URL. Everything else is refused *here as well
/// as on the server*: a malicious or stale value must degrade to the default
/// tile, never become a request to an attacker-chosen origin.
pub fn avatar_src(skin: crate::session::Skin, profile_image: &str) -> Option<String> {
    if let Some(slug) = profile_image.strip_prefix("preset:") {
        if PROFILE_ART.contains(&slug) {
            return Some(crate::asset::img(skin, slug));
        }
        return None;
    }
    if profile_image.starts_with("/api/images/") && !profile_image.contains("..") {
        return Some(profile_image.to_owned());
    }
    None
}

/// Whether a seed is a wallet address rather than a room id.
///
/// Same shape test [`monogram_for`] already applies, extracted so the art and
/// the monogram can never disagree about what they are looking at — a room
/// wearing a human face would undo the one distinction these two sets exist
/// to draw.
fn is_address(seed: &str) -> bool {
    let s = normalise(seed);
    s.len() >= 8 && s.chars().all(|c| c.is_ascii_hexdigit())
}

/// Murmur3's finalizer. djb2 is a weak hash whose high bits are dominated by
/// the *early* characters of the seed, so simply shifting right and taking a
/// remainder — the trick [`hue_for`] gets away with over 360 buckets — puts
/// every address in a set of ten onto the same face. This avalanches every
/// input bit across all 32 output bits first, which is what makes a modulo by
/// ten meaningful. Pinned by
/// `art_is_decorrelated_from_the_monogram_and_spreads_across_the_set`.
fn mix32(mut h: u32) -> u32 {
    h ^= h >> 16;
    h = h.wrapping_mul(0x85eb_ca6b);
    h ^= h >> 13;
    h = h.wrapping_mul(0xc2b2_ae35);
    h ^= h >> 16;
    h
}

/// The avatar image for a seed: an operator face for an address, a machine
/// sigil for a room.
///
/// Mixed rather than shifted, so the picture is decorrelated from both the
/// monogram (raw low bits) and the hue (raw `>> 8`): two accounts that collide
/// on the face almost never also collide on the letters or the colour.
pub fn art_for(seed: &str) -> &'static str {
    let h = mix32(djb2(&normalise(seed))) as usize;
    if is_address(seed) {
        OPERATOR_ART[h % OPERATOR_ART.len()]
    } else {
        ROOM_ART[h % ROOM_ART.len()]
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const ADDR: &str = "0x742d35cc6634c0532925a3b8d31ce5bb1c6e6b22";
    const ROOM: &str = "room_1749652739650_304e0eaf";

    #[test]
    fn djb2_matches_the_javascript_reference() {
        // The empty string is the seed value itself.
        assert_eq!(djb2(""), 5381);
        // Hand-computed: 5381*33 + 'a'(97) = 177_670.
        assert_eq!(djb2("a"), 177_670);
        // Wrapping is load-bearing: a 40-char hex string overflows u32 many
        // times over, and a non-wrapping implementation would panic in debug.
        assert_eq!(djb2(&"f".repeat(40)), djb2(&"f".repeat(40)));
    }

    #[test]
    fn an_address_wears_its_own_leading_hex() {
        // The whole point: the tile is checkable against the address printed
        // next to it. If this ever drifts to a hash-derived pair the tile
        // becomes decoration and the check silently stops being possible.
        assert_eq!(monogram_for(ADDR), "74");
        assert_eq!(
            monogram_for("0x9f2a1b3c4d5e6f708192a3b4c5d6e7f809a1b2c3"),
            "9F"
        );
    }

    #[test]
    fn a_room_id_does_not_render_as_ro() {
        // Every room id starts `room_`, so leading characters would give every
        // room in the product the same tile.
        let m = monogram_for(ROOM);
        assert_ne!(m, "RO");
        assert_eq!(m.chars().count(), 2);
        assert!(m
            .chars()
            .all(|c| c.is_ascii_alphanumeric() && !c.is_lowercase()));
    }

    #[test]
    fn a_person_never_wears_a_room_sigil_and_a_room_never_wears_a_face() {
        // The whole reason there are two sets. A room that showed a human face
        // would be indistinguishable from the person who created it in a list
        // where both appear.
        assert!(OPERATOR_ART.contains(&art_for(ADDR)));
        assert!(ROOM_ART.contains(&art_for(ROOM)));
        // Case and the `0x` prefix must not move anyone to a different face.
        assert_eq!(art_for(ADDR), art_for(&ADDR.to_uppercase()));
        assert_eq!(art_for(ADDR), art_for(ADDR.trim_start_matches("0x")));
    }

    #[test]
    fn art_is_decorrelated_from_the_monogram_and_spreads_across_the_set() {
        // Both sets must actually get used — a hash that lands every account
        // on one face is worse than no art, because it looks deliberate.
        use std::collections::HashSet;
        let faces: HashSet<_> = (0u32..600)
            .map(|i| art_for(&format!("0x{:040x}", i)))
            .collect();
        assert!(
            faces.len() >= OPERATOR_ART.len() - 1,
            "only {} of {} operator faces reachable",
            faces.len(),
            OPERATOR_ART.len()
        );
        let sigils: HashSet<_> = (0u32..600)
            .map(|i| art_for(&format!("room_1749652739650_{i:08x}")))
            .collect();
        assert!(
            sigils.len() >= ROOM_ART.len() - 1,
            "only {} of {} room sigils reachable",
            sigils.len(),
            ROOM_ART.len()
        );
    }

    #[test]
    fn every_named_asset_exists_on_disk() {
        // The lists here and the manifest in tools/genart.py are one contract
        // in two files. A name that drifts renders a broken image, which no
        // amount of logic testing would catch.
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("static/img");
        for name in OPERATOR_ART
            .iter()
            .chain(ROOM_ART.iter())
            .chain(PROFILE_ART.iter())
        {
            let path = dir.join(format!("{name}.png"));
            assert!(path.exists(), "missing generated asset: {}", path.display());
        }
    }

    #[test]
    fn a_profile_image_resolves_only_to_known_presets_and_hosted_urls() {
        // A preset from the gallery resolves to its shipped file…
        use crate::session::Skin;
        assert_eq!(
            avatar_src(Skin::Skynet, "preset:tp-coder-f").as_deref(),
            Some("/static/img/tp-coder-f.png")
        );
        // …a hosted upload resolves to itself…
        let hosted = format!("/api/images/{}.png", "a".repeat(64));
        assert_eq!(
            avatar_src(Skin::Skynet, &hosted).as_deref(),
            Some(hosted.as_str())
        );
        // A hosted upload is the user's own picture and belongs to no skin,
        // so the cute skin must not try to find a redrawn copy of it.
        assert_eq!(
            avatar_src(Skin::Cute, &hosted).as_deref(),
            Some(hosted.as_str())
        );

        // …and everything else degrades to the hash tile rather than
        // becoming a request to somewhere an attacker chose.
        for bad in [
            "preset:nonexistent",
            "preset:../../etc/passwd",
            "https://evil.example/x.png",
            "//evil.example/x.png",
            "javascript:alert(1)",
            "/api/images/../jwt.secret.png",
            "",
        ] {
            assert_eq!(avatar_src(Skin::Skynet, bad), None, "resolved {bad:?}");
        }
    }

    #[test]
    fn every_gallery_slug_pairs_a_man_and_a_woman() {
        // The gallery's promise is "each characteristic, both ways". A slug
        // whose partner is missing would render a lopsided picker.
        for slug in PROFILE_ART {
            let partner = if let Some(stem) = slug.strip_suffix("-m") {
                format!("{stem}-f")
            } else if let Some(stem) = slug.strip_suffix("-f") {
                format!("{stem}-m")
            } else {
                panic!("slug without a -m/-f suffix: {slug}");
            };
            assert!(
                PROFILE_ART.contains(&partner.as_str()),
                "{slug} has no partner {partner}"
            );
        }
    }

    #[test]
    fn gallery_labels_read_as_words() {
        assert_eq!(profile_art_label("tp-coder-f"), "Coder — woman");
        assert_eq!(profile_art_label("tp-detective-m"), "Detective — man");
    }

    #[test]
    fn a_monogram_is_always_two_printable_characters() {
        for seed in ["", "0x", "0x1", "a", ADDR, ROOM, "0X742D35CC6634C053"] {
            let m = monogram_for(seed);
            assert_eq!(m.chars().count(), 2, "wrong length for {seed:?}: {m:?}");
            assert!(!m.trim().is_empty());
        }
    }

    #[test]
    fn normalisation_is_case_insensitive_and_prefix_insensitive() {
        let mixed = "0x742d35Cc6634C0532925a3b8D31cE5bb1C6E6B22";
        let lower = ADDR;
        let bare = "742d35cc6634c0532925a3b8d31ce5bb1c6e6b22";
        let upper_prefix = "0X742D35CC6634C0532925A3B8D31CE5BB1C6E6B22";

        for form in [mixed, lower, bare, upper_prefix] {
            assert_eq!(
                monogram_for(form),
                monogram_for(lower),
                "differed for {form}"
            );
            assert_eq!(hue_for(form), hue_for(lower), "hue differed for {form}");
        }
    }

    #[test]
    fn the_same_seed_always_gets_the_same_colour() {
        for seed in [ADDR, ROOM, "0x", ""] {
            assert_eq!(hue_for(seed), hue_for(seed));
        }
    }

    #[test]
    fn colours_spread_across_the_wheel() {
        // A hue function that clusters would make every tile on screen look
        // alike, which is the one thing this is here to prevent.
        let hues: std::collections::HashSet<u16> = (0..20_000u32)
            .map(|i| hue_for(&format!("{i:040x}")))
            .collect();
        assert!(hues.iter().all(|&h| h < 360));
        // 200 rather than 360: these seeds are highly structured, so they
        // exercise only part of the hash's range. Real addresses spread
        // further; this bound is a floor, not a target.
        assert!(
            hues.len() > 200,
            "only {} distinct hues over 20k seeds",
            hues.len()
        );
    }

    /// A 40-hex-digit address whose *leading* digits actually vary.
    ///
    /// `format!("{i:040x}")` looks like an address and is useless as one here:
    /// every value under 2^32 zero-pads to the same first sixteen digits, so
    /// every tile would carry the monogram `00` and any test of spread would
    /// be measuring the formatter rather than the function.
    fn synthetic_address(i: u32) -> String {
        let v = (i as u128).wrapping_mul(0x9E37_79B9_7F4A_7C15_F39C_C060_5CED_C835);
        format!("0x{v:032x}{i:08x}")
    }

    #[test]
    fn two_different_addresses_usually_look_different() {
        // Not a guarantee — 256 hex monograms × 360 hues collide by birthday
        // at this sample size — but a pair colliding on *both* should stay
        // rare enough that a screenful of members never looks uniform.
        let mut seen = std::collections::HashSet::new();
        let mut collisions = 0;
        for i in 0..2_000u32 {
            let seed = synthetic_address(i);
            if !seen.insert((monogram_for(&seed), hue_for(&seed))) {
                collisions += 1;
            }
        }
        assert!(collisions < 120, "{collisions} collisions in 2000 seeds");
    }

    #[test]
    fn every_monogram_character_is_reachable() {
        // A tile alphabet nobody can reach half of would halve the identity
        // space while looking like it works.
        let seen: std::collections::HashSet<String> = (0..20_000u32)
            .map(|i| monogram_for(&synthetic_address(i)))
            .collect();
        assert!(seen.len() > 200, "only {} distinct monograms", seen.len());
    }

    #[test]
    fn rooms_and_people_never_share_a_seed_space_by_accident() {
        // Not a correctness requirement so much as a documented invariant:
        // room ids and addresses are different alphabets, so a room and a
        // member of it landing on the same tile is coincidence, not aliasing.
        assert_ne!(djb2(ROOM), djb2(ADDR));
    }
}
